// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-management-api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              *User_Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Roles                []string      `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Profile              *Profile      `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	SubProfiles          []*SubProfile `protobuf:"bytes,5,rep,name=sub_profiles,json=subProfiles,proto3" json:"sub_profiles,omitempty"`
	Infos                *User_Infos   `protobuf:"bytes,6,opt,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetAccount() *User_Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *User) GetSubProfiles() []*SubProfile {
	if m != nil {
		return m.SubProfiles
	}
	return nil
}

func (m *User) GetInfos() *User_Infos {
	if m != nil {
		return m.Infos
	}
	return nil
}

type User_Account struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,3,opt,name=email_confirmed,json=emailConfirmed,proto3" json:"email_confirmed,omitempty"`
	Name                 *Name    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Account) Reset()         { *m = User_Account{} }
func (m *User_Account) String() string { return proto.CompactTextString(m) }
func (*User_Account) ProtoMessage()    {}
func (*User_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{0, 0}
}

func (m *User_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Account.Unmarshal(m, b)
}
func (m *User_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Account.Marshal(b, m, deterministic)
}
func (m *User_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Account.Merge(m, src)
}
func (m *User_Account) XXX_Size() int {
	return xxx_messageInfo_User_Account.Size(m)
}
func (m *User_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Account.DiscardUnknown(m)
}

var xxx_messageInfo_User_Account proto.InternalMessageInfo

func (m *User_Account) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User_Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User_Account) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

func (m *User_Account) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type User_Infos struct {
	CreatedAt            int64    `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLogin            int64    `protobuf:"varint,3,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	LastTokenRefresh     int64    `protobuf:"varint,4,opt,name=last_token_refresh,json=lastTokenRefresh,proto3" json:"last_token_refresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Infos) Reset()         { *m = User_Infos{} }
func (m *User_Infos) String() string { return proto.CompactTextString(m) }
func (*User_Infos) ProtoMessage()    {}
func (*User_Infos) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{0, 1}
}

func (m *User_Infos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Infos.Unmarshal(m, b)
}
func (m *User_Infos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Infos.Marshal(b, m, deterministic)
}
func (m *User_Infos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Infos.Merge(m, src)
}
func (m *User_Infos) XXX_Size() int {
	return xxx_messageInfo_User_Infos.Size(m)
}
func (m *User_Infos) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Infos.DiscardUnknown(m)
}

var xxx_messageInfo_User_Infos proto.InternalMessageInfo

func (m *User_Infos) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User_Infos) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User_Infos) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *User_Infos) GetLastTokenRefresh() int64 {
	if m != nil {
		return m.LastTokenRefresh
	}
	return 0
}

type UserReference struct {
	Token                *TokenInfos `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InstanceId           string      `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserReference) Reset()         { *m = UserReference{} }
func (m *UserReference) String() string { return proto.CompactTextString(m) }
func (*UserReference) ProtoMessage()    {}
func (*UserReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{1}
}

func (m *UserReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReference.Unmarshal(m, b)
}
func (m *UserReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReference.Marshal(b, m, deterministic)
}
func (m *UserReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReference.Merge(m, src)
}
func (m *UserReference) XXX_Size() int {
	return xxx_messageInfo_UserReference.Size(m)
}
func (m *UserReference) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReference.DiscardUnknown(m)
}

var xxx_messageInfo_UserReference proto.InternalMessageInfo

func (m *UserReference) GetToken() *TokenInfos {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *UserReference) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserReference) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type RefreshTokenRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InstanceId           string   `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{2}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RefreshTokenRequest) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *RefreshTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type Name struct {
	Gender               string   `protobuf:"bytes,1,opt,name=gender,proto3" json:"gender,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{3}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Name) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Name) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Name) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type NameUpdateRequest struct {
	Token                *TokenInfos `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name                 *Name       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NameUpdateRequest) Reset()         { *m = NameUpdateRequest{} }
func (m *NameUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*NameUpdateRequest) ProtoMessage()    {}
func (*NameUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{4}
}

func (m *NameUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameUpdateRequest.Unmarshal(m, b)
}
func (m *NameUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameUpdateRequest.Marshal(b, m, deterministic)
}
func (m *NameUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameUpdateRequest.Merge(m, src)
}
func (m *NameUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_NameUpdateRequest.Size(m)
}
func (m *NameUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NameUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NameUpdateRequest proto.InternalMessageInfo

func (m *NameUpdateRequest) GetToken() *TokenInfos {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *NameUpdateRequest) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type Child struct {
	BirthYear            int32    `protobuf:"varint,1,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Gender               string   `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Child) Reset()         { *m = Child{} }
func (m *Child) String() string { return proto.CompactTextString(m) }
func (*Child) ProtoMessage()    {}
func (*Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{5}
}

func (m *Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Child.Unmarshal(m, b)
}
func (m *Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Child.Marshal(b, m, deterministic)
}
func (m *Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Child.Merge(m, src)
}
func (m *Child) XXX_Size() int {
	return xxx_messageInfo_Child.Size(m)
}
func (m *Child) XXX_DiscardUnknown() {
	xxx_messageInfo_Child.DiscardUnknown(m)
}

var xxx_messageInfo_Child proto.InternalMessageInfo

func (m *Child) GetBirthYear() int32 {
	if m != nil {
		return m.BirthYear
	}
	return 0
}

func (m *Child) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type Profile struct {
	BirthYear            int32    `protobuf:"varint,1,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	BirthMonth           int32    `protobuf:"varint,2,opt,name=birth_month,json=birthMonth,proto3" json:"birth_month,omitempty"`
	BirthDay             int32    `protobuf:"varint,3,opt,name=birth_day,json=birthDay,proto3" json:"birth_day,omitempty"`
	BirthDateUpdatedAt   int64    `protobuf:"varint,4,opt,name=birth_date_updated_at,json=birthDateUpdatedAt,proto3" json:"birth_date_updated_at,omitempty"`
	Children             []*Child `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	ChildrenUpdatedAt    int64    `protobuf:"varint,6,opt,name=children_updated_at,json=childrenUpdatedAt,proto3" json:"children_updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{6}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetBirthYear() int32 {
	if m != nil {
		return m.BirthYear
	}
	return 0
}

func (m *Profile) GetBirthMonth() int32 {
	if m != nil {
		return m.BirthMonth
	}
	return 0
}

func (m *Profile) GetBirthDay() int32 {
	if m != nil {
		return m.BirthDay
	}
	return 0
}

func (m *Profile) GetBirthDateUpdatedAt() int64 {
	if m != nil {
		return m.BirthDateUpdatedAt
	}
	return 0
}

func (m *Profile) GetChildren() []*Child {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Profile) GetChildrenUpdatedAt() int64 {
	if m != nil {
		return m.ChildrenUpdatedAt
	}
	return 0
}

type SubProfile struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BirthYear            int32    `protobuf:"varint,3,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubProfile) Reset()         { *m = SubProfile{} }
func (m *SubProfile) String() string { return proto.CompactTextString(m) }
func (*SubProfile) ProtoMessage()    {}
func (*SubProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{7}
}

func (m *SubProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubProfile.Unmarshal(m, b)
}
func (m *SubProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubProfile.Marshal(b, m, deterministic)
}
func (m *SubProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubProfile.Merge(m, src)
}
func (m *SubProfile) XXX_Size() int {
	return xxx_messageInfo_SubProfile.Size(m)
}
func (m *SubProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_SubProfile.DiscardUnknown(m)
}

var xxx_messageInfo_SubProfile proto.InternalMessageInfo

func (m *SubProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SubProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SubProfile) GetBirthYear() int32 {
	if m != nil {
		return m.BirthYear
	}
	return 0
}

type SubProfileRequest struct {
	Token                *TokenInfos `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SubProfile           *SubProfile `protobuf:"bytes,2,opt,name=sub_profile,json=subProfile,proto3" json:"sub_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SubProfileRequest) Reset()         { *m = SubProfileRequest{} }
func (m *SubProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SubProfileRequest) ProtoMessage()    {}
func (*SubProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{8}
}

func (m *SubProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubProfileRequest.Unmarshal(m, b)
}
func (m *SubProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubProfileRequest.Marshal(b, m, deterministic)
}
func (m *SubProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubProfileRequest.Merge(m, src)
}
func (m *SubProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SubProfileRequest.Size(m)
}
func (m *SubProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubProfileRequest proto.InternalMessageInfo

func (m *SubProfileRequest) GetToken() *TokenInfos {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SubProfileRequest) GetSubProfile() *SubProfile {
	if m != nil {
		return m.SubProfile
	}
	return nil
}

type ProfileRequest struct {
	Token                *TokenInfos `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Profile              *Profile    `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{9}
}

func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRequest.Unmarshal(m, b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
}
func (m *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(m, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileRequest.Size(m)
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetToken() *TokenInfos {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ProfileRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UserAuthInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles                []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	InstanceId           string   `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuthInfo) Reset()         { *m = UserAuthInfo{} }
func (m *UserAuthInfo) String() string { return proto.CompactTextString(m) }
func (*UserAuthInfo) ProtoMessage()    {}
func (*UserAuthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{10}
}

func (m *UserAuthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuthInfo.Unmarshal(m, b)
}
func (m *UserAuthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuthInfo.Marshal(b, m, deterministic)
}
func (m *UserAuthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuthInfo.Merge(m, src)
}
func (m *UserAuthInfo) XXX_Size() int {
	return xxx_messageInfo_UserAuthInfo.Size(m)
}
func (m *UserAuthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuthInfo proto.InternalMessageInfo

func (m *UserAuthInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserAuthInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *UserAuthInfo) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type PasswordChangeMsg struct {
	Token                *TokenInfos `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OldPassword          string      `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string      `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PasswordChangeMsg) Reset()         { *m = PasswordChangeMsg{} }
func (m *PasswordChangeMsg) String() string { return proto.CompactTextString(m) }
func (*PasswordChangeMsg) ProtoMessage()    {}
func (*PasswordChangeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{11}
}

func (m *PasswordChangeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordChangeMsg.Unmarshal(m, b)
}
func (m *PasswordChangeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordChangeMsg.Marshal(b, m, deterministic)
}
func (m *PasswordChangeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordChangeMsg.Merge(m, src)
}
func (m *PasswordChangeMsg) XXX_Size() int {
	return xxx_messageInfo_PasswordChangeMsg.Size(m)
}
func (m *PasswordChangeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordChangeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordChangeMsg proto.InternalMessageInfo

func (m *PasswordChangeMsg) GetToken() *TokenInfos {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *PasswordChangeMsg) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *PasswordChangeMsg) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type EmailChangeMsg struct {
	Token                *TokenInfos `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewEmail             string      `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EmailChangeMsg) Reset()         { *m = EmailChangeMsg{} }
func (m *EmailChangeMsg) String() string { return proto.CompactTextString(m) }
func (*EmailChangeMsg) ProtoMessage()    {}
func (*EmailChangeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_23188efcd8e5ff27, []int{12}
}

func (m *EmailChangeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailChangeMsg.Unmarshal(m, b)
}
func (m *EmailChangeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailChangeMsg.Marshal(b, m, deterministic)
}
func (m *EmailChangeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailChangeMsg.Merge(m, src)
}
func (m *EmailChangeMsg) XXX_Size() int {
	return xxx_messageInfo_EmailChangeMsg.Size(m)
}
func (m *EmailChangeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailChangeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EmailChangeMsg proto.InternalMessageInfo

func (m *EmailChangeMsg) GetToken() *TokenInfos {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *EmailChangeMsg) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "inf.user_management_api.User")
	proto.RegisterType((*User_Account)(nil), "inf.user_management_api.User.Account")
	proto.RegisterType((*User_Infos)(nil), "inf.user_management_api.User.Infos")
	proto.RegisterType((*UserReference)(nil), "inf.user_management_api.UserReference")
	proto.RegisterType((*RefreshTokenRequest)(nil), "inf.user_management_api.RefreshTokenRequest")
	proto.RegisterType((*Name)(nil), "inf.user_management_api.Name")
	proto.RegisterType((*NameUpdateRequest)(nil), "inf.user_management_api.NameUpdateRequest")
	proto.RegisterType((*Child)(nil), "inf.user_management_api.Child")
	proto.RegisterType((*Profile)(nil), "inf.user_management_api.Profile")
	proto.RegisterType((*SubProfile)(nil), "inf.user_management_api.SubProfile")
	proto.RegisterType((*SubProfileRequest)(nil), "inf.user_management_api.SubProfileRequest")
	proto.RegisterType((*ProfileRequest)(nil), "inf.user_management_api.ProfileRequest")
	proto.RegisterType((*UserAuthInfo)(nil), "inf.user_management_api.UserAuthInfo")
	proto.RegisterType((*PasswordChangeMsg)(nil), "inf.user_management_api.PasswordChangeMsg")
	proto.RegisterType((*EmailChangeMsg)(nil), "inf.user_management_api.EmailChangeMsg")
}

func init() {
	proto.RegisterFile("user-management-api.proto", fileDescriptor_23188efcd8e5ff27)
}

var fileDescriptor_23188efcd8e5ff27 = []byte{
	// 1093 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x86, 0xbe, 0xcd, 0xa1, 0x2d, 0xc7, 0x9b, 0xbc, 0x89, 0x5e, 0x19, 0x6e, 0x54, 0x1a, 0x69,
	0x0c, 0x23, 0x56, 0x10, 0xf7, 0xd4, 0x1c, 0x5a, 0x38, 0xb2, 0x5b, 0x18, 0xad, 0x53, 0x83, 0x8e,
	0x91, 0x26, 0x45, 0x4b, 0xac, 0xc4, 0x91, 0xb4, 0x08, 0x45, 0xb2, 0xe4, 0xb2, 0x86, 0x6f, 0xbd,
	0xf4, 0x5c, 0xa0, 0x7f, 0xad, 0xf7, 0xfe, 0x96, 0x62, 0x67, 0xb9, 0x32, 0xe5, 0x56, 0xb2, 0xdc,
	0x26, 0x27, 0x71, 0xe7, 0xe3, 0x99, 0x99, 0x67, 0x47, 0x33, 0x0b, 0xff, 0xcf, 0x52, 0x4c, 0xf6,
	0x26, 0x3c, 0xe4, 0x23, 0x9c, 0x60, 0x28, 0xf7, 0x78, 0x2c, 0xba, 0x71, 0x12, 0xc9, 0x88, 0x3d,
	0x10, 0xe1, 0xb0, 0xab, 0xd4, 0xde, 0x95, 0xda, 0xe3, 0xb1, 0x68, 0xb3, 0x51, 0x10, 0xf5, 0x79,
	0xb0, 0x27, 0x2f, 0x63, 0x4c, 0xb5, 0x71, 0x7b, 0x73, 0x14, 0x45, 0xa3, 0x00, 0x9f, 0xd2, 0xa9,
	0x9f, 0x0d, 0x9f, 0xe2, 0x24, 0x96, 0x97, 0x5a, 0xe9, 0xfc, 0x51, 0x85, 0xea, 0x79, 0x8a, 0x09,
	0x6b, 0x42, 0x59, 0xf8, 0xad, 0x52, 0xa7, 0xb4, 0x63, 0xb9, 0x65, 0xe1, 0xb3, 0x2f, 0xa0, 0xc1,
	0x07, 0x83, 0x28, 0x0b, 0x65, 0xab, 0xdc, 0x29, 0xed, 0xd8, 0xfb, 0x8f, 0xba, 0x73, 0x82, 0x76,
	0x95, 0x7f, 0xf7, 0x40, 0x1b, 0xbb, 0xc6, 0x8b, 0xdd, 0x83, 0x5a, 0x12, 0x05, 0x98, 0xb6, 0x2a,
	0x9d, 0xca, 0x8e, 0xe5, 0xea, 0x03, 0x7b, 0x0e, 0x8d, 0x38, 0x89, 0x86, 0x22, 0xc0, 0x56, 0x95,
	0x60, 0x3b, 0x73, 0x61, 0x4f, 0xb5, 0x9d, 0x6b, 0x1c, 0xd8, 0x97, 0xb0, 0x9a, 0x66, 0x7d, 0x2f,
	0x3f, 0xa6, 0xad, 0x5a, 0xa7, 0xb2, 0x63, 0xef, 0x6f, 0xcf, 0x05, 0x38, 0xcb, 0xfa, 0x06, 0xc3,
	0x4e, 0xa7, 0xdf, 0x29, 0xfb, 0x0c, 0x6a, 0x22, 0x1c, 0x46, 0x69, 0xab, 0x4e, 0x19, 0x6c, 0x2f,
	0x2e, 0xec, 0x58, 0x99, 0xba, 0xda, 0xa3, 0xfd, 0x5b, 0x09, 0x1a, 0x79, 0xa5, 0x8c, 0x41, 0x55,
	0xd1, 0x9c, 0x73, 0x46, 0xdf, 0xaa, 0x68, 0x9c, 0x70, 0x11, 0x10, 0x67, 0x96, 0xab, 0x0f, 0xec,
	0x31, 0xac, 0xd3, 0x87, 0x37, 0x88, 0xc2, 0xa1, 0x48, 0x26, 0xe8, 0xb7, 0x2a, 0x9d, 0xd2, 0xce,
	0x8a, 0xdb, 0x24, 0x71, 0xcf, 0x48, 0xd9, 0x33, 0xa8, 0x86, 0x7c, 0x62, 0xa8, 0xd9, 0x9a, 0x9b,
	0xd8, 0x4b, 0x3e, 0x41, 0x97, 0x4c, 0xdb, 0xbf, 0x97, 0xa0, 0x46, 0x29, 0xb2, 0x2d, 0x80, 0x41,
	0x82, 0x5c, 0xa2, 0xef, 0x71, 0x49, 0x59, 0x55, 0x5c, 0x2b, 0x97, 0x1c, 0x48, 0xa5, 0xce, 0x62,
	0xdf, 0xa8, 0xcb, 0x5a, 0x9d, 0x4b, 0xb4, 0x3a, 0xe0, 0xa9, 0xf4, 0x82, 0x68, 0x24, 0x42, 0x4a,
	0xaf, 0xe2, 0x5a, 0x4a, 0xf2, 0x8d, 0x12, 0xb0, 0x27, 0xc0, 0x48, 0x2d, 0xa3, 0x77, 0x18, 0x7a,
	0x09, 0x0e, 0x13, 0x4c, 0xc7, 0x94, 0x67, 0xc5, 0xbd, 0xa3, 0x34, 0xaf, 0x94, 0xc2, 0xd5, 0x72,
	0x27, 0x86, 0x35, 0xc5, 0x9d, 0x8b, 0x43, 0x4c, 0x30, 0x1c, 0x20, 0x7b, 0x04, 0x35, 0xf2, 0xa4,
	0xb4, 0xec, 0xfd, 0x75, 0xaa, 0x8c, 0x5c, 0x72, 0x7a, 0x49, 0xcb, 0x1e, 0x40, 0x83, 0xca, 0x15,
	0x7e, 0x4e, 0x60, 0x5d, 0x1d, 0x8f, 0x7d, 0xf6, 0x10, 0x6c, 0x11, 0xa6, 0x92, 0x87, 0x03, 0x54,
	0xca, 0x0a, 0x29, 0xc1, 0x88, 0x8e, 0x7d, 0x47, 0xc2, 0xdd, 0x3c, 0x78, 0x9e, 0xc8, 0x4f, 0x19,
	0xa6, 0xb2, 0x08, 0x58, 0x5a, 0x04, 0x58, 0xbe, 0x0e, 0xc8, 0xb6, 0x61, 0x2d, 0xaf, 0x52, 0xd7,
	0x9c, 0xc7, 0x5c, 0x4d, 0x0a, 0x51, 0x9c, 0x18, 0xaa, 0xea, 0x2a, 0xd8, 0x7d, 0xa8, 0x8f, 0x30,
	0xf4, 0x31, 0x31, 0x51, 0xf4, 0x49, 0xb5, 0x83, 0x14, 0x32, 0x40, 0xd3, 0x0e, 0x74, 0x50, 0x54,
	0x0f, 0x45, 0x92, 0x4a, 0x8f, 0xee, 0x5a, 0xe3, 0x5a, 0x24, 0x21, 0xb0, 0x4d, 0x20, 0xde, 0xbd,
	0x69, 0x27, 0x58, 0xee, 0x8a, 0x12, 0x28, 0xa5, 0x33, 0x81, 0x0d, 0xf5, 0x7b, 0x4e, 0xf7, 0x66,
	0xaa, 0x5c, 0x92, 0x5d, 0xd3, 0x5d, 0xe5, 0xa5, 0xbb, 0xcb, 0xf9, 0x1c, 0x6a, 0xbd, 0xb1, 0x08,
	0x7c, 0x95, 0x73, 0x5f, 0x24, 0x72, 0xec, 0x5d, 0x22, 0xd7, 0x55, 0xd6, 0x5c, 0x8b, 0x24, 0x6f,
	0x90, 0x27, 0x05, 0x02, 0xca, 0x45, 0x02, 0x9c, 0x5f, 0xcb, 0xd0, 0xc8, 0xff, 0x77, 0x37, 0x41,
	0x3c, 0x04, 0x5b, 0xab, 0x27, 0x51, 0x28, 0xc7, 0x84, 0x53, 0x73, 0xb5, 0xc7, 0x89, 0x92, 0x28,
	0x5e, 0xb4, 0x81, 0xcf, 0x2f, 0x89, 0xb5, 0x9a, 0xbb, 0x42, 0x82, 0x43, 0x7e, 0xc9, 0x9e, 0xc1,
	0xff, 0x8c, 0x52, 0xa2, 0x57, 0x68, 0x74, 0xdd, 0xa2, 0x2c, 0x37, 0x94, 0x39, 0x73, 0xaa, 0xe3,
	0x9f, 0xc3, 0xca, 0x40, 0xd5, 0x96, 0x60, 0x98, 0x8f, 0x92, 0x8f, 0xe6, 0x52, 0x42, 0x24, 0xb8,
	0x53, 0x7b, 0xd6, 0x85, 0xbb, 0xe6, 0xbb, 0x18, 0xac, 0x4e, 0xc1, 0x36, 0x8c, 0x6a, 0x1a, 0xcb,
	0xf9, 0x16, 0xe0, 0x6a, 0x1a, 0xfd, 0x6d, 0xd6, 0xb2, 0xc2, 0xc5, 0x58, 0x9a, 0xf9, 0x6b, 0x6c,
	0x55, 0xae, 0xb1, 0xe5, 0xfc, 0x52, 0x82, 0x8d, 0xc2, 0x7c, 0xbb, 0x5d, 0x23, 0x1c, 0x82, 0x5d,
	0x18, 0xa4, 0x79, 0x3f, 0x2c, 0x35, 0x47, 0xe1, 0x6a, 0x8e, 0x3a, 0x29, 0x34, 0xff, 0x5d, 0xf8,
	0xc2, 0x0e, 0x28, 0xdf, 0x72, 0x07, 0x38, 0x3f, 0xc2, 0xaa, 0x9a, 0x2c, 0x07, 0x99, 0x1c, 0x2b,
	0xcc, 0xf9, 0x7f, 0xf0, 0xe9, 0xfa, 0x29, 0x17, 0xd7, 0xcf, 0x8d, 0x73, 0x44, 0xf1, 0x7a, 0xca,
	0xd3, 0xf4, 0x22, 0x4a, 0xfc, 0xde, 0x98, 0x87, 0x23, 0x3c, 0x49, 0x47, 0xcb, 0x16, 0xf6, 0x31,
	0xac, 0x46, 0x81, 0xef, 0xc5, 0xb9, 0x7f, 0x7e, 0x9f, 0x76, 0x14, 0xf8, 0x06, 0x52, 0x99, 0x84,
	0x78, 0x71, 0x65, 0xa2, 0x33, 0xb0, 0x43, 0xbc, 0x30, 0x26, 0xce, 0x2b, 0x68, 0x1e, 0xd1, 0x5a,
	0xb8, 0x6d, 0xf8, 0x4d, 0xb0, 0x14, 0x76, 0x71, 0x01, 0xad, 0x84, 0x78, 0x41, 0x60, 0xfb, 0x7f,
	0x5a, 0xb0, 0xa1, 0x98, 0x3b, 0x99, 0x12, 0x7c, 0x10, 0x0b, 0xb6, 0x07, 0xf5, 0x33, 0xc9, 0x65,
	0x96, 0xb2, 0xfb, 0x5d, 0xfd, 0x4c, 0xe8, 0x9a, 0x67, 0x42, 0xf7, 0x48, 0x3d, 0x13, 0xda, 0x36,
	0x05, 0xcb, 0x8d, 0x4e, 0xa0, 0x49, 0xeb, 0xe0, 0xb5, 0x90, 0x63, 0x82, 0x65, 0xf7, 0x48, 0xad,
	0x80, 0x7b, 0x09, 0xfa, 0x18, 0x4a, 0xc1, 0x83, 0xb4, 0xbd, 0xf8, 0xad, 0x30, 0xbd, 0xbc, 0x97,
	0xb0, 0x7e, 0x26, 0x46, 0x61, 0x16, 0xbf, 0x37, 0xbc, 0x8d, 0xde, 0x18, 0x07, 0xef, 0x8a, 0x9b,
	0x80, 0x3d, 0x99, 0xeb, 0xfb, 0x0f, 0x0b, 0x63, 0xb6, 0xdc, 0xaf, 0xa1, 0x59, 0x5c, 0x6b, 0xe8,
	0xff, 0x17, 0xb0, 0x53, 0x68, 0x7c, 0x85, 0x92, 0xde, 0x5a, 0x9f, 0x2c, 0x2c, 0x67, 0xba, 0x35,
	0xdb, 0x5b, 0x0b, 0xed, 0xd8, 0x31, 0x34, 0x75, 0x8f, 0x4c, 0xbb, 0x6b, 0x77, 0xfe, 0x1f, 0xe9,
	0x7a, 0x4f, 0xcf, 0x26, 0x77, 0x0e, 0xb6, 0xd6, 0xe8, 0x5b, 0x78, 0x3c, 0x17, 0x67, 0xb6, 0x33,
	0x6f, 0xca, 0xf0, 0x35, 0x80, 0x9e, 0x81, 0xb4, 0xd8, 0x76, 0x17, 0x6e, 0x9c, 0x99, 0x95, 0x76,
	0x13, 0xf0, 0x21, 0xac, 0x1d, 0x62, 0x80, 0x12, 0xcd, 0x63, 0x6c, 0x59, 0x4a, 0x67, 0xaa, 0x7e,
	0x03, 0xeb, 0x3a, 0xea, 0x0b, 0xb3, 0x1d, 0x16, 0x54, 0x3e, 0x3b, 0xeb, 0x6e, 0x4a, 0xf0, 0x3b,
	0x68, 0x6a, 0xe8, 0x9e, 0x59, 0x19, 0xef, 0x0b, 0xf9, 0x2d, 0xac, 0x1d, 0xf8, 0xfe, 0x59, 0xd6,
	0x37, 0xcf, 0xe2, 0xdd, 0x65, 0x06, 0xf7, 0x72, 0xd8, 0xdf, 0x43, 0xf3, 0xc8, 0x17, 0xf2, 0xc3,
	0x80, 0xff, 0x00, 0x77, 0x5c, 0x9c, 0x44, 0x3f, 0xe3, 0x07, 0x81, 0x7f, 0x51, 0x7b, 0x5b, 0xe1,
	0xb1, 0xe8, 0xd7, 0x69, 0x7e, 0x7d, 0xfa, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x66, 0x91,
	0x21, 0x3e, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserManagementApiClient is the client API for UserManagementApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserManagementApiClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	// Auth and Token handling:
	LoginWithEmail(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*UserAuthInfo, error)
	SignupWithEmail(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*UserAuthInfo, error)
	CheckRefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*Status, error)
	TokenRefreshed(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*Status, error)
	// User properties:
	GetUser(ctx context.Context, in *UserReference, opts ...grpc.CallOption) (*User, error)
	// Account methods:
	ChangePassword(ctx context.Context, in *PasswordChangeMsg, opts ...grpc.CallOption) (*Status, error)
	ChangeEmail(ctx context.Context, in *EmailChangeMsg, opts ...grpc.CallOption) (*User, error)
	UpdateName(ctx context.Context, in *NameUpdateRequest, opts ...grpc.CallOption) (*User, error)
	DeleteAccount(ctx context.Context, in *UserReference, opts ...grpc.CallOption) (*Status, error)
	// Profile methods:
	UpdateBirthDate(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*User, error)
	UpdateChildren(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*User, error)
	AddSubprofile(ctx context.Context, in *SubProfileRequest, opts ...grpc.CallOption) (*User, error)
	EditSubprofile(ctx context.Context, in *SubProfileRequest, opts ...grpc.CallOption) (*User, error)
	RemoveSubprofile(ctx context.Context, in *SubProfileRequest, opts ...grpc.CallOption) (*User, error)
}

type userManagementApiClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagementApiClient(cc grpc.ClientConnInterface) UserManagementApiClient {
	return &userManagementApiClient{cc}
}

func (c *userManagementApiClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) LoginWithEmail(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*UserAuthInfo, error) {
	out := new(UserAuthInfo)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/LoginWithEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) SignupWithEmail(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*UserAuthInfo, error) {
	out := new(UserAuthInfo)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/SignupWithEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) CheckRefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/CheckRefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) TokenRefreshed(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/TokenRefreshed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) GetUser(ctx context.Context, in *UserReference, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) ChangePassword(ctx context.Context, in *PasswordChangeMsg, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) ChangeEmail(ctx context.Context, in *EmailChangeMsg, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/ChangeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) UpdateName(ctx context.Context, in *NameUpdateRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/UpdateName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) DeleteAccount(ctx context.Context, in *UserReference, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) UpdateBirthDate(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/UpdateBirthDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) UpdateChildren(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/UpdateChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) AddSubprofile(ctx context.Context, in *SubProfileRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/AddSubprofile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) EditSubprofile(ctx context.Context, in *SubProfileRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/EditSubprofile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementApiClient) RemoveSubprofile(ctx context.Context, in *SubProfileRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/inf.user_management_api.UserManagementApi/RemoveSubprofile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagementApiServer is the server API for UserManagementApi service.
type UserManagementApiServer interface {
	Status(context.Context, *empty.Empty) (*Status, error)
	// Auth and Token handling:
	LoginWithEmail(context.Context, *UserCredentials) (*UserAuthInfo, error)
	SignupWithEmail(context.Context, *UserCredentials) (*UserAuthInfo, error)
	CheckRefreshToken(context.Context, *RefreshTokenRequest) (*Status, error)
	TokenRefreshed(context.Context, *RefreshTokenRequest) (*Status, error)
	// User properties:
	GetUser(context.Context, *UserReference) (*User, error)
	// Account methods:
	ChangePassword(context.Context, *PasswordChangeMsg) (*Status, error)
	ChangeEmail(context.Context, *EmailChangeMsg) (*User, error)
	UpdateName(context.Context, *NameUpdateRequest) (*User, error)
	DeleteAccount(context.Context, *UserReference) (*Status, error)
	// Profile methods:
	UpdateBirthDate(context.Context, *ProfileRequest) (*User, error)
	UpdateChildren(context.Context, *ProfileRequest) (*User, error)
	AddSubprofile(context.Context, *SubProfileRequest) (*User, error)
	EditSubprofile(context.Context, *SubProfileRequest) (*User, error)
	RemoveSubprofile(context.Context, *SubProfileRequest) (*User, error)
}

// UnimplementedUserManagementApiServer can be embedded to have forward compatible implementations.
type UnimplementedUserManagementApiServer struct {
}

func (*UnimplementedUserManagementApiServer) Status(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedUserManagementApiServer) LoginWithEmail(ctx context.Context, req *UserCredentials) (*UserAuthInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithEmail not implemented")
}
func (*UnimplementedUserManagementApiServer) SignupWithEmail(ctx context.Context, req *UserCredentials) (*UserAuthInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupWithEmail not implemented")
}
func (*UnimplementedUserManagementApiServer) CheckRefreshToken(ctx context.Context, req *RefreshTokenRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRefreshToken not implemented")
}
func (*UnimplementedUserManagementApiServer) TokenRefreshed(ctx context.Context, req *RefreshTokenRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenRefreshed not implemented")
}
func (*UnimplementedUserManagementApiServer) GetUser(ctx context.Context, req *UserReference) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserManagementApiServer) ChangePassword(ctx context.Context, req *PasswordChangeMsg) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedUserManagementApiServer) ChangeEmail(ctx context.Context, req *EmailChangeMsg) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEmail not implemented")
}
func (*UnimplementedUserManagementApiServer) UpdateName(ctx context.Context, req *NameUpdateRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateName not implemented")
}
func (*UnimplementedUserManagementApiServer) DeleteAccount(ctx context.Context, req *UserReference) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (*UnimplementedUserManagementApiServer) UpdateBirthDate(ctx context.Context, req *ProfileRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBirthDate not implemented")
}
func (*UnimplementedUserManagementApiServer) UpdateChildren(ctx context.Context, req *ProfileRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChildren not implemented")
}
func (*UnimplementedUserManagementApiServer) AddSubprofile(ctx context.Context, req *SubProfileRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSubprofile not implemented")
}
func (*UnimplementedUserManagementApiServer) EditSubprofile(ctx context.Context, req *SubProfileRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditSubprofile not implemented")
}
func (*UnimplementedUserManagementApiServer) RemoveSubprofile(ctx context.Context, req *SubProfileRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSubprofile not implemented")
}

func RegisterUserManagementApiServer(s *grpc.Server, srv UserManagementApiServer) {
	s.RegisterService(&_UserManagementApi_serviceDesc, srv)
}

func _UserManagementApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_LoginWithEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).LoginWithEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/LoginWithEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).LoginWithEmail(ctx, req.(*UserCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_SignupWithEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).SignupWithEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/SignupWithEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).SignupWithEmail(ctx, req.(*UserCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_CheckRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).CheckRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/CheckRefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).CheckRefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_TokenRefreshed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).TokenRefreshed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/TokenRefreshed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).TokenRefreshed(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).GetUser(ctx, req.(*UserReference))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordChangeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).ChangePassword(ctx, req.(*PasswordChangeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailChangeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/ChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).ChangeEmail(ctx, req.(*EmailChangeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_UpdateName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).UpdateName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/UpdateName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).UpdateName(ctx, req.(*NameUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).DeleteAccount(ctx, req.(*UserReference))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_UpdateBirthDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).UpdateBirthDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/UpdateBirthDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).UpdateBirthDate(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_UpdateChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).UpdateChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/UpdateChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).UpdateChildren(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_AddSubprofile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).AddSubprofile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/AddSubprofile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).AddSubprofile(ctx, req.(*SubProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_EditSubprofile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).EditSubprofile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/EditSubprofile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).EditSubprofile(ctx, req.(*SubProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementApi_RemoveSubprofile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementApiServer).RemoveSubprofile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.user_management_api.UserManagementApi/RemoveSubprofile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementApiServer).RemoveSubprofile(ctx, req.(*SubProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManagementApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inf.user_management_api.UserManagementApi",
	HandlerType: (*UserManagementApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _UserManagementApi_Status_Handler,
		},
		{
			MethodName: "LoginWithEmail",
			Handler:    _UserManagementApi_LoginWithEmail_Handler,
		},
		{
			MethodName: "SignupWithEmail",
			Handler:    _UserManagementApi_SignupWithEmail_Handler,
		},
		{
			MethodName: "CheckRefreshToken",
			Handler:    _UserManagementApi_CheckRefreshToken_Handler,
		},
		{
			MethodName: "TokenRefreshed",
			Handler:    _UserManagementApi_TokenRefreshed_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserManagementApi_GetUser_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserManagementApi_ChangePassword_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _UserManagementApi_ChangeEmail_Handler,
		},
		{
			MethodName: "UpdateName",
			Handler:    _UserManagementApi_UpdateName_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _UserManagementApi_DeleteAccount_Handler,
		},
		{
			MethodName: "UpdateBirthDate",
			Handler:    _UserManagementApi_UpdateBirthDate_Handler,
		},
		{
			MethodName: "UpdateChildren",
			Handler:    _UserManagementApi_UpdateChildren_Handler,
		},
		{
			MethodName: "AddSubprofile",
			Handler:    _UserManagementApi_AddSubprofile_Handler,
		},
		{
			MethodName: "EditSubprofile",
			Handler:    _UserManagementApi_EditSubprofile_Handler,
		},
		{
			MethodName: "RemoveSubprofile",
			Handler:    _UserManagementApi_RemoveSubprofile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-management-api.proto",
}
